spring:
  datasource:
    url: jdbc:mysql:{url/"database-name"}
    username: "{username}"
    password: "{pass}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: "{if you dont have database(create) after set it to (update)}"
    show-sql: true
    propertiens:
      hibernate:
        format_sql: true
  

